### ISSUE TITLE
Docs bug

### ISSUE THREAD

**Issue by krzysztof-grzybek** [supermedium/issues#10]
Hi!
I want to report little misleading bug in [aframe-supercraft-thing](https://www.npmjs.com/package/aframe-supercraft-thing) docs. 

In `npm` section package names are type without `aframe` prefix: `supercraft-thing` instead of `aframe-supercraft-thing` and `supercraft-loader` instead of `aframe-supercraft-loader`.

Also, on npm page there is broken link to github repo.

**Comment by ngokevin** [comment]
Thanks, will have it fixed soon.

**Comment by ngokevin** [comment]
Fixed!
