### ISSUE TITLE
Controller not displayed with Oculus Rift

### ISSUE THREAD

**Issue by smeybi** [supermedium/issues#12]
In the Main Menu of Supermedium the controller is not displayed with Oculus Rift, only the laserpoint.

**Comment by smeybi** [comment]
Update: The controllers are sometimes displayed, sometimes not.

**Comment by ngokevin** [comment]
Thanks for the issue, I’ve seen it as well. We will take a look.

**Comment by ngokevin** [comment]
I will update today with bumped version of A-Frame to fix.

**Comment by ngokevin** [comment]
Should be fixed now.
