### ISSUE TITLE
[Supermedium] HTC Vive Tracker selected as Controller

### ISSUE THREAD

**Issue by smeybi** [supermedium/issues#13]
Since update of SteamVR to the version 1.3.22. In the main menu of Supermedium, the tracker is taken as a controller again. It worked, before the update (1-2 days ago).
Also in the content(website/Aframe) the tracker taken as controller.
I can not give any more information because firefox no longer recognizes the tracker at all.
I will test it with another pc and report if it is not the same issue there.

**Comment by smeybi** [comment]
It works with my other pc correct. Something is strange, it worked well, now it does not work properly anymore. I'll try that out right and find out why this occurs.

**Comment by ngokevin** [comment]
Thanks for the report. At least on the home screen I can try to get it to ignore trackers but no guarantees on the content yet

**Comment by smeybi** [comment]
Do not change anything yet. I have uninstalled and reinstalled Supermedium and now works fine again! 
No problem in the homescreen, even if the tracker is on, no problem in the content. Probably settings change after the SteamVR update on this pc. 
Sorry for the too fast report!
I do not know why there was a problem yesterday. I will observe this and report it if necessary. 
Thanks for the help!

**Comment by ngokevin** [comment]
Please report if you see it again! Seriously, thank you for taking your time to report an issue. Hope to seriously improve Supermedium in the coming months.
