### ISSUE TITLE
[Supermedium] Aframe 9 website not change always in vr mode

### ISSUE THREAD

**Issue by smeybi** [supermedium/issues#14]
Hi
I have noticed, that website's with aframe 9.1 and a lot of content, in supermedium not change in vr-mode.
Not with all computer, only the weaker have this issue.
I have tested with 2 computer. With the Personal Computer(GTX 1080) start fine, with the Notebook (GTX 1070) it does not change into the vr-mode.
I have tested almost same website, aframe 7 works, aframe 9.1 not. Website's with small content and aframe 9.1 works.
I have also tested another website(not mine, a featured), which have a lot of content and aframe 9, the same issue. But the second try, it worked. I think, because loaded content was in the cache.

I hope it is useful information.

**Comment by ngokevin** [comment]
Thanks for the issue, we'll look into this and patch on A-Frame.

**Comment by smeybi** [comment]
Update:
Now there is the same issue with the other computer(the stronger). So I think it is not the power of the computer, but something else, maybe the loading time.
I have tested also the other website(Blue Cyber), the same issue, no starting. Then the second try, it runs. After delete the cache, no starting.
I tried it and delete content, script and assets. Without script and without assets it works. Without script and with assets it doesn't work. I think, it is something with the loading time.
Here the link: https://towermax.fitness/tower_beta_a9tutorial

**Comment by ngokevin** [comment]
Thanks for the details. Planning to update A-Frame. Let me know if this build solves for you https://send.firefox.com/download/7e291160787863c1/#_wNGmRx8X_WrAltAC-strw

**Comment by smeybi** [comment]
No, it does not work with the new script.
I have send you an email ..@sup.....

**Comment by ngokevin** [comment]
Thanks! https://twitter.com/supermediumvr/status/1125554528005181440
